# Generated by Django 6.0.4 on 2026-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTag',
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portifolio.skill'),
        ),
    ]
