# Generated by Django 6.0.4 on 2026-04-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_delete_projecttag_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='portifolio.skill'),
        ),
    ]
