# Generated by Django 6.0.4 on 2026-04-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_project_image_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True),
        ),
    ]
