# Generated by Django 6.0.4 on 2026-04-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_experience_description_en_experience_position_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description_en',
            new_name='description_pt',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='position_en',
            new_name='position_pt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_en',
            new_name='description_pt',
        ),
    ]
